#!/bin/sh
#SBATCH --job-name=SPEAD_global_cont
#SBATCH --time=04-12:00:00     # run no longer than 60 hours
#SBATCH --mem-per-cpu=2500
#SBATCH --ntasks=40
#SBATCH --output=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D/OUTPUT/META-DATA/SLURM_OUTPUT
#SBATCH --error=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D/OUTPUT/META-DATA/SLURM_ERROR
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bsauterey@icm.csic.es

export initdir=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D
export rundir=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D/OUTPUT/META-DATA/Run_final_mutT_1e2_mutS_1e3_mutL_1e3_new_higherPARoptmin_noLMaxcap/
mkdir $rundir
cp $initdir/mitgcmuv $rundir
cp $initdir/POLY3.COEFFS $rundir
cp $initdir/data $rundir
cp $initdir/eedata $rundir
cp $initdir/data.* $rundir
cp $initdir/data $rundir
cp $initdir/pickup* $rundir
cp -r $initdir/../code_offline3D/ $rundir
sleep 10s

cd $rundir
mpirun -np 40 ./mitgcmuv
sleep 10s

