#!/bin/sh
#SBATCH --job-name=SPEAD_global_cont
#SBATCH --time=04-12:00:00     # run no longer than 60 hours
#SBATCH --mem-per-cpu=2500
#SBATCH --ntasks=40
#SBATCH --output=./OUTPUT/META-DATA/SLURM_OUTPUT
#SBATCH --error=./OUTPUT/META-DATA/SLURM_ERROR

export initdir=.
export rundir=$initdir/OUTPUT/META-DATA/your_run/
export exe=mitgcmuv_DD
mkdir $rundir
cp $initdir/$exe $rundir
cp $initdir/POLY3.COEFFS $rundir
cp $initdir/data $rundir
cp $initdir/eedata $rundir
cp $initdir/data.* $rundir
cp $initdir/data $rundir
cp $initdir/pickup* $rundir
cp -r $initdir/../code_offline3D/ $rundir
sleep 10s

cd $rundir
mpirun -np 40 ./$exe
sleep 10s

