#!/bin/sh
#SBATCH --job-name=SPEAD_global_cont
#SBATCH --time=04-12:00:00     # run no longer than 60 hours
#SBATCH --mem-per-cpu=2500
#SBATCH --ntasks=32
#SBATCH --output=/home/sauterey/BORIS/MIT-GIT/DARWIN/OFFLINE-3D/runs_offline3D/OUTPUT/META-DATA/SLURM_OUTPUT
#SBATCH --error=/home/sauterey/BORIS/MIT-GIT/DARWIN/OFFLINE-3D/runs_offline3D/OUTPUT/META-DATA/SLURM_ERROR
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bsauterey@icm.csic.es

export initdir=/home/sauterey/BORIS/MIT-GIT/DARWIN/OFFLINE-3D/runs_offline3D/
export rundir=/home/sauterey/BORIS/MIT-GIT/DARWIN/OFFLINE-3D/runs_offline3D/OUTPUT/META-DATA/test_3/
mkdir $rundir
cp $initdir/mitgcmuv $rundir
cp $initdir/POLY3.COEFFS $rundir
cp $initdir/data $rundir
cp $initdir/eedata $rundir
cp $initdir/data.* $rundir
cp $initdir/data $rundir
cp $initdir/pickup* $rundir
cp $initdir/../code_offline3D/darwin_tempfunc.F $rundir
cp $initdir/../code_offline3D/darwin_plankton.F $rundir
cp $initdir/../code_offline3D/darwin_spead_rates.F $rundir
sleep 10s

cd $rundir
mpirun -np 32 ./mitgcmuv
sleep 10s

