#!/bin/sh
#SBATCH --job-name=SPEAD_global_cont
#SBATCH --time=04-12:00:00     # run no longer than 60 hours
#SBATCH --mem=48G
#SBATCH --ntasks=24
#SBATCH --output=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D_CChange/OUTPUT/META-DATA/SLURM_OUTPUT
#SBATCH --error=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D_CChange/OUTPUT/META-DATA/SLURM_ERROR
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bsauterey@icm.csic.es

export initdir=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D_CChange
export rundir=/home/sauterey/BORIS/MIT-GIT/DARWIN/SPEAD_cont_3D/runs_offline3D_CChange/OUTPUT/META-DATA/Co_sim/
mkdir $rundir
cp $initdir/mitgcmuv $rundir
cp $initdir/POLY3.COEFFS $rundir
cp $initdir/data $rundir
cp $initdir/eedata $rundir
cp $initdir/data.* $rundir
cp $initdir/data $rundir
cp $initdir/pickup* $rundir
cp -r $initdir/../code_offline3D_CChange/ $rundir
sleep 10s

cd $rundir
mpirun -np 24 ./mitgcmuv
sleep 10s

